#!/usr/bin/ruby

puts "Welcome to the Missile Command installer."
puts "This will install xcode, brew, rbenv, and ruby if you don't already have them."
puts "This can take up to 10 minutes depending on your internet speed"
puts "Is this ok? [Y/N]"

response = gets.chomp
if response.casecmp("y") != 0
  puts "You did not agree.  Terminating..."
  exit
end

module OS
  def self.windows?
    (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end

  def self.mac?
   (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def self.unix?
    !OS.windows?
  end

  def self.linux?
    OS.unix? and not OS.mac?
  end
end

def install_brew
  if system("which brew > /dev/null")
    puts "Brew is installed already... skipping."
  else
    puts "Installing brew, the Mac package manager"
    unless system("/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"")
      puts "Error: you need brew to fetch a dependency.  Please install brew and then re-run this script."
      exit
    end
  end
end

def install_sdl2
  # Install SDL2
  if system("brew ls --versions sdl2 > /dev/null")
    puts "SDL2 is installed already... skipping."
  else
    puts "Installing sdl2, a gaming library"
    unless system("brew install sdl2")
      puts "Error: unable to install a dependency.  Please make sure that \"brew install sdl2\" succeeds, then re-run this file"
      exit
    end
  end
end

def install_rbenv
  if system("which rbenv > /dev/null")
    puts "rbenv is installed already... skipping."
  else
    puts "Installing rbenv, a Ruby version manager"
    instructions = [
      "brew install rbenv ruby-build",
      "echo 'if which rbenv > /dev/null; then eval \"$(rbenv init -)\"; fi' >> ~/.bash_profile",
      "source ~/.bash_profile"
    ]
    unless instructions.all? { |i| system(i) }
      puts "Error: unable to install rbenv.  Please make sure each of these steps succeeds"
      instructions.each { |i| puts "  " + i }
      exit
    end
  end
end

def install_ruby
  ruby_version = File.read(".ruby-version").chomp
  if system("rbenv local #{ruby_version}")
    puts "Ruby #{ruby_version} is installed already... skipping."
  else
    puts "Installing Ruby #{ruby_version}"
    instructions = [
      "rbenv install #{ruby_version}",
      "rbenv local #{ruby_version}",
      "source ~/.bash_profile"
    ]
    unless instructions.all? { |i| system(i) }
      puts "Error: unable to install Ruby #{ruby_version}.  Please make sure \"rbenv install #{ruby_version}\" succeeds"
    end
  end
end

def install_gosu
  if system("gem list | grep gosu > /dev/null")
    puts "Gosu is installed already... skipping."
  else
    puts "Installing gosu, a Ruby wrapper for sdl2"
    unless system("gem install gosu")
      puts "Error: unable to install gosu.  Please make sure \"gem install gosu\" succeeds, then re-run this file."
      exit
    end
  end
end

def install_shortcut
  return if system("cat ~/.bash_profile | grep missile_command > /dev/null")
  shortcut = "function missile() { cd ~/Downloads/missile_command; ruby missile_command.rb }"
  system("echo '#{shortcut}' >> ~/.bash_profile")
  system("source ~/.bash_profile")
end

def perform_mac_install
  install_brew
  install_sdl2
  install_rbenv
  install_ruby
  install_gosu
  install_shortcut
  puts "Installation successful!"
  puts "Type missile to launch game"
end

def perform_linux_install
  puts "Please run the following commands:"
  puts "sudo apt-get update && sudo apt-get install libsdl2-dev"
  puts "rbenv local 2.1.6"
  puts "gem install gosu"
  puts "ruby missile_command.rb"
  puts "Any questions email me at michael[dot]zemel[at]gmail[dot]com"
end

if OS.mac?
  perform_mac_install
elsif OS.linux?
  perform_linux_install
else
  puts "Your operating system is not supported, sorry!"
  exit
end

