1:
  spaceships:
    number: 3
  battleships:
    number: 0
  fortresses:
    number: 0
  bunkers:
    number: 1
    ammo: 10
    health: medium
  defenders:
    number: 0
  planet: endor

2:
  spaceships:
    number: 5
    height: medium
    weapons: easy
  battleships:
    number: 0
  fortresses:
    number: 0
  bunkers:
    number: 1
    ammo: 10
    health: medium
  defenders:
    number: 0
  planet: hoth

3:
  spaceships:
    number: 0
  battleships:
    number: 0
  fortresses:
    number: 1
    weapons: medium
  bunkers:
    number: 2
    ammo: 15
    health: medium
  defenders:
    number: 1
    mode: medium
    height: high
    weapons: hard
  planet: tatooine

4:
  spaceships:
    number: 3
    height: low
    mode: hard
    weapons: medium
  battleships:
    number: 1
    mode: medium
    weapons: easy
  fortresses:
    number: 0
  bunkers:
    number: 2
    ammo: 5
    health: medium
  defenders:
    number: 1
    mode: medium
    height: high
    weapons: hard
  planet: naboo

5:
  spaceships:
    number: 5
    height: medium
    mode: hard
    weapons: hard
    number: 4
    ammo: 5
  battleships:
    number: 1
    mode: medium
    weapons: medium
    height: medium
    health: medium
  fortresses:
    number: 0
  bunkers:
    number: 2
    ammo: 8
    health: medium
  defenders:
    number: 2
    height: high
    weapons: medium
    health: medium
  planet: yavin_4

6:
  spaceships:
    number: 5
    height: high
    mode: hard
    weapons: medium
  battleships:
    number: 1
    mode: hard
    weapons: medium
    height: medium
    health: medium
  fortresses:
    number: 1
    weapons: medium
  bunkers:
    number: 3
    ammo: 10
    health: medium
  defenders:
    number: 1
    height: high
    weapons: hard
    health: medium
  planet: tatooine

7:
  spaceships:
    number: 8
    height: medium
    mode: medium
    weapons: hard
  battleships:
    number: 1
    mode: hard
    weapons: hard
    health: medium
  fortresses:
    number: 0
  bunkers:
    number: 3
    ammo: 10
    health: medium
  defenders:
    number: 2
    height: high
    weapons: easy
    health: medium
  planet: naboo

8:
  spaceships:
    number: 10
    height: high
    mode: hard
    weapons: hard
  battleships:
    number: 2
    mode: medium
    weapons: medium
    health: medium
  fortresses:
    number: 0
  bunkers:
    number: 3
    ammo: 12
    health: medium
  defenders:
    number: 1
    height: high
    weapons: easy
  planet: hoth

9:
  spaceships:
    number: 6
    height: low
    mode: hard
    weapons: hard
  battleships:
    number: 3
    mode: medium
    weapons: hard
    health: medium
  fortresses:
    number: 2
    weapons: hard
  bunkers:
    number: 4
    ammo: 15
    health: medium
  defenders:
    number: 0
  planet: tatooine

10:
  spaceships:
    number: 100
  battleships:
    number: 0
  fortresses:
    number: 0
  bunkers:
    number: 1
    ammo: 10
  defenders:
    number: 0
  planet: naboo
