1:
  spaceships:
    number: 3
  battleships:
    number: 0
  fortresses:
    number: 0
  bunkers:
    number: 1
    ammo: 10
    health: medium
  defenders:
    number: 0
  planet: yavin_4
  music: main_theme_1.mp3

2:
  spaceships:
    number: 5
    height: medium
    weapons: medium
  battleships:
    number: 0
  fortresses:
    number: 0
  bunkers:
    number: 1
    ammo: 10
    health: medium
  defenders:
    number: 0
  planet: hoth
  music: main_theme_2.mp3

3:
  spaceships:
    number: 0
  battleships:
    number: 0
  fortresses:
    number: 1
    weapons: insane
  bunkers:
    number: 2
    ammo: 8
    health: medium
  defenders:
    number: 0
  planet: tatooine
  music: cantina.mp3

4:
  spaceships:
    number: 3
    height: low
    mode: hard
    weapons: medium
  battleships:
    number: 1
    mode: medium
    weapons: easy
  fortresses:
    number: 0
  bunkers:
    number: 2
    ammo: 5
    health: medium
  defenders:
    number: 1
    mode: medium
    height: high
    weapons: hard
  planet: naboo
  music: duel_of_the_fates.mp3

5:
  spaceships:
    number: 5
    height: medium
    mode: hard
    weapons: hard
    number: 4
    ammo: 5
  battleships:
    number: 1
    mode: medium
    weapons: medium
    height: medium
    health: medium
  fortresses:
    number: 0
  bunkers:
    number: 2
    ammo: 8
    health: medium
  defenders:
    number: 2
    height: high
    weapons: medium
    health: medium
  planet: endor
  music: ewok.mp3

6:
  spaceships:
    number: 5
    height: high
    mode: hard
    weapons: medium
  battleships:
    number: 1
    mode: hard
    weapons: medium
    height: medium
    health: medium
  fortresses:
    number: 1
    weapons: medium
  bunkers:
    number: 3
    ammo: 8
    health: medium
  defenders:
    number: 1
    height: high
    weapons: hard
    health: medium
  planet: tatooine
  music: cantina.mp3

7:
  spaceships:
    number: 8
    height: medium
    mode: medium
    weapons: hard
  battleships:
    number: 2
    mode: hard
    weapons: hard
    health: medium
  fortresses:
    number: 0
  bunkers:
    number: 3
    ammo: 10
    health: medium
  defenders:
    number: 2
    height: high
    weapons: easy
    health: medium
  planet: naboo
  music: duel_of_the_fates.mp3

8:
  spaceships:
    number: 10
    height: high
    mode: hard
    weapons: hard
  battleships:
    number: 2
    mode: medium
    weapons: medium
    health: medium
  fortresses:
    number: 0
  bunkers:
    number: 3
    ammo: 10
    health: medium
  defenders:
    number: 1
    height: high
    weapons: easy
  planet: hoth
  music: main_theme_2.mp3

9:
  spaceships:
    number: 0
  battleships:
    number: 5
    mode: medium
    weapons: hard
    health: medium
  fortresses:
    number: 1
    weapons: hard
  bunkers:
    number: 4
    ammo: 15
    health: medium
  defenders:
    number: 0
  planet: endor
  music: ewok.mp3

10:
  spaceships:
    number: 100
  battleships:
    number: 0
  fortresses:
    number: 0
  bunkers:
    number: 1
    ammo: 10
  defenders:
    number: 0
  planet: naboo
  music: duel_of_the_fates.mp3
