one:
  spaceships:
    number: 3
  battleships:
    number: 0
  bunkers:
    number: 1
    ammo: 10
    health: medium
  defenders:
    number: 0

two:
  spaceships:
    number: 5
    height: medium
    weapons: easy
  battleships:
    number: 0
  bunkers:
    number: 1
    ammo: 10
    health: medium
  defenders:
    number: 0

three:
  spaceships:
    number: 7
    height: low
    mode: medium
    weapons: easy
  battleships:
    number: 1
  bunkers:
    number: 2
    ammo: 10
    health: medium
  defenders:
    number: 1
    mode: medium
    height: high
    weapons: hard

four:
  spaceships:
    number: 3
    height: low
    mode: hard
    weapons: medium
  battleships:
    number: 1
    mode: medium
    weapons: easy
  bunkers:
    number: 2
    ammo: 10
    health: medium
  defenders:
    number: 1
    mode: medium
    height: high
    weapons: hard

five:
  spaceships:
    number: 5
    height: medium
    mode: hard
    weapons: hard
    number: 4
    ammo: 5
  battleships:
    number: 1
    mode: medium
    weapons: medium
    height: medium
    health: medium
  bunkers:
    number: 2
    ammo: 10
    health: medium
  defenders:
    number: 2
    height: high
    weapons: medium
    health: medium

six:
  spaceships:
    number: 5
    height: high
    mode: hard
    weapons: medium
  battleships:
    number: 1
    mode: hard
    weapons: medium
    height: medium
    health: medium
  bunkers:
    number: 3
    ammo: 10
    health: medium
  defenders:
    number: 1
    height: high
    weapons: hard
    health: medium

seven:
  spaceships:
    number: 8
    height: medium
    mode: medium
    weapons: hard
  battleships:
    number: 1
    mode: hard
    weapons: hard
    health: medium
  bunkers:
    number: 3
    ammo: 12
    health: medium
  defenders:
    number: 2
    height: high
    weapons: easy
    health: medium

eight:
  spaceships:
    number: 10
    height: high
    mode: hard
    weapons: hard
  battleships:
    number: 2
    mode: medium
    weapons: medium
    health: medium
  bunkers:
    number: 3
    ammo: 12
    health: medium
  defenders:
    number: 1
    height: high
    weapons: easy

nine:
  spaceships:
    number: 6
    height: low
    mode: hard
    weapons: hard
  battleships:
    number: 3
    mode: medium
    weapons: hard
    health: medium
  bunkers:
    number: 4
    ammo: 10
    health: medium
  defenders:
    number: 0

ten:
  spaceships:
    number: 10
    mode: hard
    weapons: hard
  battleships:
    number: 2
    mode: hard
    weapons: hard
    health: low
  bunkers:
    number: 4
    ammo: 12
    health: medium
  defenders:
    number: 0

