one:
  enemies:
    number: 3
    height: high
    mode: easy
    weapons: false
    health: hard
  bunkers:
    number: 1
    ammo: 10
  defenders:
    number: 0

two:
  enemies:
    number: 5
    height: medium
    mode: easy
    weapons: easy
  bunkers:
    number: 1
    ammo: 15
  defenders:
    number: 0

three:
  enemies:
    number: 7
    height: low
    mode: medium
    weapons: easy
  bunkers:
    number: 2
    ammo: 10
  defenders:
    number: 1
    ammo: 5
    mode: medium
    height: high
    weapons: hard

four:
  enemies:
    number: 3
    height: low
    mode: hard
    weapons: medium
  bunkers:
    number: 2
    ammo: 5
  defenders:
    number: 1
    ammo: 5
    mode: medium
    height: high
    weapons: hard

five:
  enemies:
    number: 5
    height: medium
    mode: hard
    weapons: hard
  bunkers:
    number: 4
    ammo: 5
  defenders:
    number: 2
    ammo: 3
    mode: easy
    height: high
    weapons: medium

six:
  enemies:
    number: 5
    height: high
    mode: hard
    weapons: medium
  bunkers:
    number: 3
    ammo: 2
  defenders:
    number: 2
    ammo: 3
    mode: easy
    height: high
    weapons: medium

seven:
  enemies:
    number: 5
    height: medium
    mode: hard
    weapons: hard
  bunkers:
    number: 4
    ammo: 5
  defenders:
    number: 2
    ammo: 3
    mode: easy
    height: high
    weapons: easy

eight:
  enemies:
    number: 8
    height: high
    mode: hard
    weapons: hard
  bunkers:
    number: 4
    ammo: 3
  defenders:
    number: 1
    ammo: 5
    mode: easy
    height: high
    weapons: easy

nine:
  enemies:
    number: 10
    height: low
    mode: hard
    weapons: hard
  bunkers:
    number: 4
    ammo: 4
  defenders:
    number: 0

ten:
  enemies:
    number: 20
    height: high
    mode: medium
    weapons: medium
  bunkers:
    number: 4
    ammo: 5
  defenders:
    number: 0

